---
# POC Cognit – frontend-only inventory for one-deploy + cognit packages.
# Edge hosts are provisioned by oneprovision (stock onprem driver),
# NOT by one-deploy directly. Set their IPs in edge_host_ips below.

all:
  vars:
    ansible_user: root
    ansible_ssh_extra_args: "-o ForwardAgent=yes"
    update_pkg_cache: true
    ensure_hostname: true
    ensure_hosts: true
    one_version: "7.1"
    # Disable one-deploy's built-in opennebula repo setup (we use our private repo)
    repos_enabled: [ceph, frr, grafana]
    one_pass: opennebulapass
    db_backend: SQLite
    features:
      provision: true
    # Allow pip install of ansible-core for oneadmin on Python 3.12+ (PEP 668)
    _pip_extra_args: "--break-system-packages"
    # Edge host IPs for oneprovision (stock onprem driver)
    edge_host_ips:
      - 172.20.0.78
      # - 172.20.0.X  # add more as needed
    ds:
      mode: ssh
    vn:
      admin_net:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth0
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 172.20.0.100
            SIZE: 48
          NETWORK_ADDRESS: 172.20.0.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 172.20.0.1
          DNS: 1.1.1.1

frontend:
  hosts:
    f1:
      ansible_host: 172.20.0.4

node:
  hosts: {}
