---
# POC Cognit – frontend-only inventory for one-deploy + cognit package.
# Replace ansible_host with your Ubuntu 24 frontend VM IP.

all:
  vars:
    ansible_user: root
    ansible_ssh_extra_args: "-o ForwardAgent=yes"
    update_pkg_cache: true
    ensure_hostname: true
    ensure_hosts: true
    one_version: "7.1"
    # Disable one-deploy's built-in opennebula repo setup
    repos_enabled: [ceph, frr, grafana]
    one_pass: opennebulapass
    db_backend: SQLite
    ds:
      mode: ssh
    vn:
      admin_net:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth0
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 172.20.0.100
            SIZE: 48
          NETWORK_ADDRESS: 172.20.0.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 172.20.0.1
          DNS: 1.1.1.1

frontend:
  hosts:
    f1:
      ansible_host: 172.20.0.4  # TODO: set to your Ubuntu 24 VM IP

node:
  hosts: {}  # empty, required by one-deploy common role