---
# One command: OpenNebula frontend first, then Cognit repo + package.
# Run: ansible-playbook -i poc/cognit/inventory.yml poc/cognit/run-all.yml
- name: Set hostname from inventory (so precheck passes)
  hosts: frontend
  gather_facts: true
  tasks:
    - name: Set hostname to inventory name
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

- ansible.builtin.import_playbook: opennebula.deploy.pre
- ansible.builtin.import_playbook: opennebula.deploy.site
- ansible.builtin.import_playbook: playbook.yml
